create table public.visitas_col (
  id_visita bigint generated by default as identity not null,
  "RBD" bigint not null,
  nom_col character varying not null,
  inscritos bigint not null,
  fecha_visita date not null,
  created_at timestamp with time zone not null default now(),
  comuna bigint null,
  region bigint null,
  nom_com text null,
  constraint visitas_col_pkey primary key (id_visita)
) TABLESPACE pg_default;